databases:
  - name: localhost-postgresql
    type: postgresql
    root_user: postgres
    root_password: postgres
    host: localhost
    port: 5432

  - name: prod-postgresql
    type: postgresql
    root_user: root
    root_password: secret
    host: production.server.aws
    port: 5432
